### ISSUE TITLE
login.php 오타

### ISSUE THREAD

**Issue by vsc0705** [kumryung/showdown-manager#2]
https://github.com/kumryung/showdown-manager/blob/3b672daef2845d250f10fd49b140ca295af27ac4/login.php#L24

사소한 오타지만 첫화면에 딱 보이니까 신경이 쓰이네요 ㅋㅋ

**Comment by kumryung** [comment]
아.. 수정하겠습니다 ㅎㅎ

2019년 5월 27일 (월) 오후 1:38, vsc0705 <notifications@github.com>님이 작성:

**Comment by vsc0705** [comment]
헉 확인이 빠르시네요
감사히 사용하고 있습니다 ㅋㅋ
